import { Showcase } from "./Showcase";
import { Slides } from "./Slides";
import { Cursor } from "./Cursor";
import image1 from "../images/1.png";
import image2 from "../images/1.png";
import image3 from "../images/1.png";
import image4 from "../images/1.png";
import image5 from "../images/1.png";

const container = document.getElementById("app");
const cursor = new Cursor(document.querySelector(".cursor"));
const slidesData = [
  {
    image: image1,
    title: "المعرفة أساس الوصول",
    heenaba: "",
    monzo: "",
    noheetoka: "",
    betawaslna: "",
    sharakoona: "",
    belebdaa:"",
    kaddamna: "",
    ettasel: "",
    wasaloo: "",
    abdaana: "",
    khadamat: "",
    takhteet: "",
    takhteett: "",
    sinaa: "",
    sinaaa: "",
    edara: "",
    edaraa: "",
    tahseen: "",
    ketaba: "",
    arkam: "",
    hakakna: "",
    zohor: "",
    katabna:"",
    mohtawa:"",
    nafazna:"",
    graphic:"",
    antjna:"",
    maktaa:"",
    aalna:"",
    molen:"",
    aladl:"",
    aladllogo:"",
    mosalaha:"",
    mosalahalogo:"",
    stc:"",
    stclogo:"",
    zamlia:"",
    emkan:"",
    logo6:"",
    logo7:"",
    logo8:"",
    logo9:"",
    logo10:"",
    logo11:"",
    logo12:"",
    logo13:"",
    logo14:"",
    logo15:"",
    logo16:"",
    logo17:"",
    logo18:"",
    logo19:"",
    logo20:"",
    logo21:"",
    logo22:"",
    logo23:"",
    logo24:"",
    email:"",
    emaill:"",
    location:"",
    locationn:"",
    heena:"",
    biglogo:"<img src='https://abdullaomar.com/wp-content/uploads/2023/02/Untitled-design.png' style='width:100%; height:100%;'>",
    madeby:"<a href='https://abdullaomar.com'><img class='alignnone wp-image-1833' src='https://i.ibb.co/PTSznKp/Abdullah-1.png' alt='' width='155' height='30' style='border-radius: 5px;' /></a>"
  },
  {
    image: image2,
    title: "",
    heena:"حين تود الإنطلاق نرسم لك مسارك",
    heenaba: ",حين بدأنا",
    monzo: "منذ 10 سنوات .. انطلقنا في رحلة غامرة بتفاصيلها، في عالم التسويق الإلكتروني والإعلام الرقمي، وصرنا أكثر دراية بمساراته المختلفة والمتنوعة، وقدرة على تحديد الوجهة لكل من أراد الانطلاق والوصول، بفريق يمتلك مهارة عالية وخبرات متعددة، يقوم بأداء مهامه على أكمل وجه، لنصل نحن وشركاؤنا ونحقق الأهداف",
    noheetoka: "",
    betawaslna: "",
    sharakoona: "",
    belebdaa:"",
    kaddamna: "",
    ettasel: "",
    wasaloo: "",
    abdaana: "",
    khadamat: "",
    takhteet: "",
    takhteett: "",
    sinaa: "",
    sinaaa: "",
    edara: "",
    edaraa: "",
    tahseen: "",
    ketaba: "",
    arkam: "",
    hakakna: "",
    zohor: "",
    katabna:"",
    mohtawa:"",
    nafazna:"",
    graphic:"",
    antjna:"",
    maktaa:"",
    aalna:"",
    molen:"",
    aladl:"",
    aladllogo:"",
    mosalaha:"",
    mosalahalogo:"",
    stc:"",
    stclogo:"",
    zamlia:"",
    emkan:"",
    logo6:"",
    logo7:"",
    logo8:"",
    logo9:"",
    logo10:"",
    logo11:"",
    logo12:"",
    logo13:"",
    logo14:"",
    logo15:"",
    logo16:"",
    logo17:"",
    logo18:"",
    logo19:"",
    logo20:"",
    logo21:"",
    logo22:"",
    logo23:"",
    logo24:"",
    email:"",
    emaill:"",
    location:"",
    locationn:"",
    biglogo:"",
    madeby:""
  },
  {
    image: image3,
    title: "",
    heenaba: "",
    monzo: "",
    noheetoka: "! نحيطك علمًا دعمًا، لتحقق حلمًا",
    betawaslna: "",
    sharakoona: "",
    belebdaa:"",
    kaddamna: ",قدمنا",
    ettasel: "",
    wasaloo: "",
    abdaana: "",
    khadamat: "خدمات عديدة، استطعنا من خلالها تحقيق أهداف شركائنا",
    takhteet: ":تخطيط وتنفيذ الحملات التسويقية",
    takhteett: "تخطيط حملات تسويقية متكاملة، وتنفيذها باحترافية عالية، من خلال استخدام وسائل التسويق الرقمي، ووسائل الإعلام التقليدي، إضافة إلى إعلانات المشاهير والمؤثرين، وإعلانات الطرق",
    sinaa: ":صناعة المحتوى الإبداعي",
    sinaaa: "صناعة محتوى إبداعي بما يتناسب مع جميع منصات التواصل، وذلك بعد ابتكار الأفكار الإبداعية، وتحديد الجمهور، واختيار نوع المحتوى وشكله وأسلوبه",
    edara: ":إدارة حسابات وسائل التواصل الاجتماعي",
    edaraa: "إدارة جميع حسابات العملاء على مختلف المنصات، من خلال نشر المحتوى المناسب لها، والتفاعل فيها مع الجمهور، والرد على استفساراتهم",
    tahseen: ":(SEO) تحسين محركات البحث",
    ketaba: "كتابة محتوى خاص ليتناسب مع محركات البحث، باستخدام الكلمات المناسبة، وكتابة العناوين الواضحة والجذابة، لرفع نسبة ظهور مواقع العملاء وتعزيز وصولها",
    arkam: "",
    hakakna: "",
    zohor: "",
    katabna:"",
    mohtawa:"",
    nafazna:"",
    graphic:"",
    antjna:"",
    maktaa:"",
    aalna:"",
    molen:"",
    aladl:"",
    aladllogo:"",
    mosalaha:"",
    mosalahalogo:"",
    stc:"",
    stclogo:"",
    zamlia:"",
    emkan:"",
    logo6:"",
    logo7:"",
    logo8:"",
    logo9:"",
    logo10:"",
    logo11:"",
    logo12:"",
    logo13:"",
    logo14:"",
    logo15:"",
    logo16:"",
    logo17:"",
    logo18:"",
    logo19:"",
    logo20:"",
    logo21:"",
    logo22:"",
    logo23:"",
    logo24:"",
    email:"",
    emaill:"",
    location:"",
    locationn:"",
    heena:"",
    biglogo:"",
    madeby:""
  },
  {
    image: image4,
    title: "",
    heenaba: "",
    monzo: "",
    noheetoka: "",
    betawaslna: "",
    sharakoona: "",
    belebdaa:"! بالإبداع صُلنا، حتى وصلنا",
    kaddamna: "",
    ettasel: "",
    wasaloo: "",
    abdaana: ",أبدعنا",
    khadamat: "",
    takhteet: "",
    takhteett: "",
    sinaa: "",
    sinaaa: "",
    edara: "",
    edaraa: "",
    tahseen: "",
    ketaba: "",
    arkam: ":أرقام وإحصاءات",
    hakakna: "",
    zohor: "<img src='https://i.ibb.co/Fn2p0S8/zohoor.webp' style='width:100%; height:100%; border-radius:20px;'>",
    katabna:"",
    mohtawa:"<img src='https://i.ibb.co/Xjjrwrx/mohtawa.webp' style='width:100%; height:100%; border-radius:20px;'>",
    nafazna:"",
    graphic:"<img src='https://i.ibb.co/9wRrTnf/graphic.webp' style='width:100%; height:100%; border-radius:20px;'>",
    antjna:"",
    maktaa:"<img src='https://i.ibb.co/WVxw0pT/makta3.webp' style='width:100%; height:100%; border-radius:20px;'>",
    aalna:"",
    molen:"<img src='https://i.ibb.co/hZC88kR/molen.webp' style='width:100%; height:100%; border-radius:20px;'>",
    aladl:"",
    aladllogo:"",
    mosalaha:"",
    mosalahalogo:"",
    stc:"",
    stclogo:"",
    zamlia:"",
    emkan:"",
    logo6:"",
    logo7:"",
    logo8:"",
    logo9:"",
    logo10:"",
    logo11:"",
    logo12:"",
    logo13:"",
    logo14:"",
    logo15:"",
    logo16:"",
    logo17:"",
    logo18:"",
    logo19:"",
    logo20:"",
    logo21:"",
    logo22:"",
    logo23:"",
    logo24:"",
    email:"",
    emaill:"",
    location:"",
    locationn:"",
    heena:"",
    biglogo:"",
    madeby:""
  },
  {
    image: image5,
    title: "",
    heenaba: "",
    monzo: "",
    noheetoka: "",
    betawaslna: "",
    sharakoona: "!شاركونا الرحلة وشاركناهم الإبداع",
    belebdaa:"",
    kaddamna: "",
    ettasel: "",
    wasaloo: ",وصلوا معنا",
    abdaana: "",
    khadamat: "",
    takhteet: "",
    takhteett: "",
    sinaa: "",
    sinaaa: "",
    edara: "",
    edaraa: "",
    tahseen: "",
    ketaba: "",
    arkam: "",
    hakakna: "",
    zohor: "",
    katabna:"",
    mohtawa:"",
    nafazna:"",
    graphic:"",
    antjna:"",
    maktaa:"",
    aalna:"",
    molen:"",
    aladl:"",
    aladllogo:"<img src='https://i.ibb.co/vdW57P4/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    mosalaha:"",
    mosalahalogo:"<img src='https://i.ibb.co/wLb615Q/Untitled-design-6.png' style='width:100%; height:100%; border-radius:10px;'>",
    stc:"",
    stclogo:"<img src='https://i.ibb.co/hF5NDNf/Untitled-design-1.png' style='width:100%; height:100%; border-radius:10px;'>",
    zamlia:"<img src='https://i.ibb.co/Y215fC1/Untitled-design-2.png' style='width:100%; height:100%; border-radius:10px;'>",
    emkan:"<img src='https://i.ibb.co/mqsgzz8/Untitled-design-3.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo6:"<img src='https://i.ibb.co/7ykXYmv/Untitled-design-4.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo7:"<img src='https://i.ibb.co/jvgvMGb/Untitled-design-5.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo8:"<img src='https://i.ibb.co/1TWpfJR/Untitled-design-7.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo9:"<img src='https://i.ibb.co/g3C2rTB/Untitled-design-8.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo10:"<img src='https://i.ibb.co/fnmGhYx/Untitled-design-9.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo11:"<img src='https://i.ibb.co/Pw6R8jk/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo12:"<img src='https://i.ibb.co/c34rVkW/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo13:"<img src='https://i.ibb.co/Hp3YYXg/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo14:"<img src='https://i.ibb.co/kDQN7sm/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo15:"<img src='https://i.ibb.co/KDxcG5w/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo16:"<img src='https://i.ibb.co/VmpQmW0/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo17:"<img src='https://i.ibb.co/HFys9Ss/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo18:"<img src='https://i.ibb.co/YkcTNFt/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo19:"<img src='https://i.ibb.co/fYk2Gwf/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo20:"<img src='https://i.ibb.co/fHm9LZb/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo21:"<img src='https://i.ibb.co/VQ2KWB9/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo22:"<img src='https://i.ibb.co/VLK4ppJ/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo23:"<img src='https://i.ibb.co/xgg87RQ/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    logo24:"<img src='https://i.ibb.co/YdBK28G/Untitled-design.png' style='width:100%; height:100%; border-radius:10px;'>",
    email:"",
    emaill:"",
    location:"",
    locationn:"",
    heena:"",
    biglogo:"",
    madeby:""
  },
  {
    image: image4,
    title: "",
    heenaba: "",
    monzo: "",
    noheetoka: "",
    betawaslna: "بتواصلنا نبدأ رحلتنا",
    sharakoona: "",
    belebdaa:"",
    kaddamna: "",
    ettasel: ",إتصل بنا",
    wasaloo: "",
    abdaana: "",
    khadamat: "",
    takhteet: "",
    takhteett: "",
    sinaa: "",
    sinaaa: "",
    edara: "",
    edaraa: "",
    tahseen: "",
    ketaba: "",
    arkam: "",
    hakakna: "",
    zohor: "",
    katabna:"",
    mohtawa:"",
    nafazna:"",
    graphic:"",
    antjna:"",
    maktaa:"",
    aalna:"",
    molen:"",
    aladl:"",
    aladllogo:"",
    mosalaha:"",
    mosalahalogo:"",
    stc:"",
    stclogo:"",
    zamlia:"",
    emkan:"",
    logo6:"",
    logo7:"",
    logo8:"",
    logo9:"",
    logo10:"",
    logo11:"",
    logo12:"",
    logo13:"",
    logo14:"",
    logo15:"",
    logo16:"",
    logo17:"",
    logo18:"",
    logo19:"",
    logo20:"",
    logo21:"",
    logo22:"",
    logo23:"",
    logo24:"",
    email:" <i class='fa fa-envelope' style='color: #490E66;'></i> ",
    emaill:"info@knowhow.sa",
    location:"<i class='fa fa-map-marker' style='color: #490E66;'></i>",
    locationn:"المملكة العربية السعودية، الرياض، حي الروضة، شارع خالد بن الوليد 13211",
    heena:"",
    biglogo:"",
    madeby:""
  }
];

const slides = new Slides(slidesData);
const showcase = new Showcase(slidesData, {
  onActiveIndexChange: activeIndex => {
    slides.onActiveIndexChange(activeIndex);
  },
  onIndexChange: index => {
    slides.onMove(index);
  },
  onZoomOutStart: ({ activeIndex }) => {
    cursor.enter();
    slides.appear();
  },
  onZoomOutFinish: ({ activeIndex }) => {},
  onFullscreenStart: ({ activeIndex }) => {
    cursor.leave();
    slides.disperse(activeIndex);
  },
  onFullscreenFinish: ({ activeIndex }) => {}
});

showcase.mount(container);
slides.mount(container);
showcase.render();

window.addEventListener("resize", function() {
  showcase.onResize();
});

window.addEventListener("mousemove", function(ev) {
  showcase.onMouseMove(ev);
});
